"""Data models and type definitions for ZeroDay ML vulnerability detection pipeline."""

from __future__ import annotations

import enum
from dataclasses import asdict, dataclass, field
from typing import Any


class InputType(enum.StrEnum):
    """Supported input modalities for vulnerability detection."""
    CODE = "code"
    HTTP_TRAFFIC = "http_traffic"
    URL = "url"


@dataclass
class PipelineInput:
    """Raw input submitted to the ZeroDay detection pipeline."""
    input_type: InputType
    content: str  # Source code, raw HTTP request string, or URL string
    target_id: str = "default_target"
    filepath: str = ""
    language: str = ""  # c, cpp, python, java, etc.
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        res = asdict(self)
        res["input_type"] = self.input_type.value
        return res


@dataclass
class CandidateFinding:
    """Initial candidate detection generated by the fine-tuned classifier."""
    is_vulnerable: bool
    confidence: float  # 0.0 to 1.0
    detected_class: str  # e.g. "SQL_INJECTION", "BUFFER_OVERFLOW", "PHISHING", etc.
    candidate_cwes: list[str] = field(default_factory=list)
    raw_scores: dict[str, float] = field(default_factory=dict)
    salient_tokens: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class ExtractedEvidence:
    """Localized evidence pinpointing where and how the vulnerability manifests."""
    snippet: str = ""
    start_line: int | None = None
    end_line: int | None = None
    parameter_name: str | None = None
    http_component: str | None = None  # path, query, header, body
    decoded_payload: str | None = None
    matched_patterns: list[str] = field(default_factory=list)
    entropy_score: float | None = None
    structural_tokens: list[str] = field(default_factory=list)
    context_lines: list[tuple[int, str]] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class ReasoningHypothesis:
    """Hypothesis generated by LLM reasoning grounded in NVD/CWE data."""
    is_plausible: bool
    plausibility_score: float  # 0.0 to 1.0
    attack_path: str = ""
    root_cause_analysis: str = ""
    primary_cwe: str = ""
    alternative_cwes: list[str] = field(default_factory=list)
    suggested_cvss_vector: str = ""
    suggested_severity: str = "MEDIUM"
    nvd_references: list[dict[str, Any]] = field(default_factory=list)
    prerequisites: list[str] = field(default_factory=list)
    impact_assessment: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class VerificationResult:
    """Result of independent verification using secondary deterministic engines."""
    agreed: bool
    verifier_method: str  # "ast_taint_rule", "grammar_parser", "lexical_heuristic", etc.
    confidence: float  # 0.0 to 1.0
    reasons: list[str] = field(default_factory=list)
    secondary_cwe: str | None = None
    evidence_confirmed: bool = False
    details: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class FilterResult:
    """False-positive filter evaluation output."""
    is_filtered: bool
    rejection_reason: str = ""
    sanitizer_detected: bool = False
    sanitizer_type: str | None = None
    is_dead_code: bool = False
    is_test_fixture: bool = False
    reachability_score: float = 1.0  # 0.0 to 1.0
    filter_confidence: float = 1.0  # 0.0 to 1.0

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class ScoringResult:
    """Standardized CWE mapping and CVSS scoring output."""
    cwe_id: str
    cwe_name: str
    cvss_score: float
    cvss_vector: str
    severity: str  # "CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"
    composite_confidence: float  # Factoring candidate, verification, and filter confidence
    owasp_category: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class PipelineReport:
    """Complete end-to-end audit report for a processed input."""
    target_id: str
    input_type: InputType
    is_vulnerable: bool
    status: str  # "CONFIRMED", "REJECTED_FILTER", "REJECTED_VERIFICATION", "CLEAN"
    candidate: CandidateFinding
    evidence: ExtractedEvidence
    reasoning: ReasoningHypothesis
    verification: VerificationResult
    filter_result: FilterResult
    scoring: ScoringResult | None = None
    finding_record: dict[str, Any] | None = None
    processing_time_ms: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        res = asdict(self)
        res["input_type"] = self.input_type.value
        return res
