"""Purple Team Engine for ZeroDay v2.0."""

from __future__ import annotations

import logging
from dataclasses import asdict, dataclass, field
from typing import Any


logger = logging.getLogger(__name__)


@dataclass
class PurpleTeamResult:
    attack_id: str
    technique_id: str
    technique_name: str
    attack_successful: bool
    telemetry_generated: bool
    telemetry_collected: bool
    detection_triggered: bool
    alert_generated: bool
    alert_actionable: bool
    gap_summary: str = ""

    @property
    def outcome(self) -> str:
        if self.attack_successful and not self.detection_triggered:
            return "ATTACK_SUCCESS_DETECTION_FAILED"
        elif self.attack_successful and self.detection_triggered:
            return "ATTACK_SUCCESS_DETECTION_SUCCESS"
        elif not self.attack_successful and self.detection_triggered:
            return "ATTACK_BLOCKED_DETECTION_SUCCESS"
        else:
            return "ATTACK_BLOCKED"

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["outcome"] = self.outcome
        return d


class PurpleTeamEngine:
    """Evaluates offensive action against defensive telemetry, alerting, and controls."""

    def __init__(self) -> None:
        self._results: list[PurpleTeamResult] = []

    def evaluate_attack(
        self,
        *,
        attack_id: str,
        technique_id: str,
        technique_name: str,
        attack_successful: bool,
        telemetry_generated: bool,
        telemetry_collected: bool,
        detection_triggered: bool,
        alert_generated: bool = False,
        alert_actionable: bool = False,
    ) -> PurpleTeamResult:
        gaps = []
        if not telemetry_generated:
            gaps.append("Telemetry not generated by target system")
        elif not telemetry_collected:
            gaps.append("Telemetry generated locally but not ingested into central SIEM")
        elif not detection_triggered:
            gaps.append("Telemetry collected in SIEM but no detection rule fired")
        elif not alert_generated:
            gaps.append("Detection fired but failed to create SOC alert")
        elif not alert_actionable:
            gaps.append("Alert created but missing crucial context/evidence for triage")

        gap_summary = "; ".join(gaps) if gaps else "No detection gaps identified"

        res = PurpleTeamResult(
            attack_id=attack_id,
            technique_id=technique_id,
            technique_name=technique_name,
            attack_successful=attack_successful,
            telemetry_generated=telemetry_generated,
            telemetry_collected=telemetry_collected,
            detection_triggered=detection_triggered,
            alert_generated=alert_generated,
            alert_actionable=alert_actionable,
            gap_summary=gap_summary,
        )
        self._results.append(res)
        return res

    def get_summary(self) -> dict[str, Any]:
        total = len(self._results)
        detection_failed = sum(
            1 for r in self._results if r.attack_successful and not r.detection_triggered
        )
        detection_success = sum(
            1 for r in self._results if r.attack_successful and r.detection_triggered
        )
        blocked = sum(1 for r in self._results if not r.attack_successful)

        return {
            "total_evaluations": total,
            "detection_failures": detection_failed,
            "detection_successes": detection_success,
            "blocked_attacks": blocked,
            "detection_rate": (
                round((detection_success / (detection_failed + detection_success)) * 100, 1)
                if (detection_failed + detection_success) > 0
                else 100.0
            ),
            "evaluations": [r.to_dict() for r in self._results],
        }
